[tool.poetry]
name = "llm-switcher"
version = "0.1.0"
description = ""
authors = ["Jordan Plows  <jordan@lightapi.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
